/* 
Scenario
Little Lemon needs to build a robust relational database system in MySQL in which they can store large amounts of data. 
They then need to easily manage and find this data as required. This database system should maintain information about 
the following aspects of the business:  
- Bookings: To store information about booked tables in the restaurant including booking id, date and table number.
- Orders:  To store information about each order such as order date, quantity and total cost.
- Order delivery status: To store information about the delivery status of each order such as delivery date and status.
- Menu: To store information about cuisines, starters, courses, drinks and desserts.
- Customer details: To store information about the customer names and contact details.
- and Staff information: Including role and salary.
*/

-- MySQL Script generated by MySQL Workbench
-- Sun Jul 28 22:25:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDB` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemonDB` ;

-- -----------------------------------------------------
-- Table `mydb`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`bookings` (
  `booking_id` INT NOT NULL,
  `booking_date` DATE NULL,
  `table_nr` INT NULL,
  PRIMARY KEY (`booking_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`order_status` (
  `order_id` INT NOT NULL,
  `delivery_date` DATE NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`orders` (
  `order_id` INT NOT NULL,
  `booking_id` INT NULL,
  `quantity` INT NULL,
  `total_cost` DECIMAL NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_bookings_idx` (`booking_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_bookings`
    FOREIGN KEY (`booking_id`)
    REFERENCES `LittleLemonDB`.`bookings` (`booking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_order_status1`
    FOREIGN KEY (`order_id`)
    REFERENCES `LittleLemonDB`.`order_status` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`menu` (
  `menu_id` INT NOT NULL,
  `cuisine` VARCHAR(45) NULL,
  `starter` VARCHAR(45) NULL,
  `course` VARCHAR(45) NULL,
  `drink` VARCHAR(45) NULL,
  `dessert` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `menucol` VARCHAR(45) NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`order_menu` (
  `order_id` INT NOT NULL,
  `menu_id` INT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_menu_menu1_idx` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_menu_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `LittleLemonDB`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_menu_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `LittleLemonDB`.`menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`customer_details` (
  `custormer_id` INT NOT NULL,
  `customer_name` VARCHAR(45) NULL,
  `customer_contact` VARCHAR(45) NULL,
  PRIMARY KEY (`custormer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`staff` (
  `staff_id` INT NOT NULL,
  `staff_name` VARCHAR(45) NULL,
  `staff_role` VARCHAR(45) NULL,
  `salary` DECIMAL NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
